server:
  port: 8099


spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8
    cache: true

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/test?useUnicode=true
      username: root
      password: 123456


logs:
  level: debug

constant:
  path: src/main/resources/data/
  fileName: acrtmsfcz00000001.txt

